create extension if not exists btree_gist;
create table profiles(id uuid primary key references auth.users on delete cascade,name text not null,phone text,role text not null check(role in('admin','barber')),barber_id uuid,created_at timestamptz default now());
create table barbers(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,phone text,photo_url text,bio text,specialties text[] default '{}',active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
alter table profiles add constraint profiles_barber_fk foreign key(barber_id) references barbers;
create table services(id text primary key,name text not null,slug text unique not null,description text,price numeric(10,2) not null check(price>=0),duration_minutes int check(duration_minutes>0),image_url text,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table barber_services(id bigint generated always as identity primary key,barber_id uuid references barbers on delete cascade,service_id text references services on delete cascade,unique(barber_id,service_id));
create table working_hours(id bigint generated always as identity primary key,barber_id uuid references barbers on delete cascade,weekday int check(weekday between 0 and 6),start_time time not null,end_time time not null,active boolean default true,check(start_time<end_time));
create table breaks(id bigint generated always as identity primary key,barber_id uuid references barbers on delete cascade,weekday int check(weekday between 0 and 6),start_time time not null,end_time time not null);
create table blocked_times(id uuid primary key default gen_random_uuid(),barber_id uuid references barbers on delete cascade,start_datetime timestamptz not null,end_datetime timestamptz not null,reason text,created_at timestamptz default now(),check(start_datetime<end_datetime));
create table customers(id uuid primary key default gen_random_uuid(),name text not null,phone text unique not null,notes text,created_at timestamptz default now(),updated_at timestamptz default now());
create table appointments(id uuid primary key default gen_random_uuid(),customer_id uuid references customers,barber_id uuid references barbers,service_id text references services,appointment_date date not null,start_datetime timestamptz not null,end_datetime timestamptz not null,price numeric(10,2) not null,status text not null default 'aguardando confirmação' check(status in('aguardando confirmação','confirmado','concluído','cancelado','não compareceu')),customer_notes text,internal_notes text,created_at timestamptz default now(),updated_at timestamptz default now(),check(start_datetime<end_datetime));
alter table appointments add constraint no_overlapping_appointments exclude using gist (barber_id with =,tstzrange(start_datetime,end_datetime,'[)') with &&) where (status not in ('cancelado','não compareceu'));
create index appointments_start_idx on appointments(start_datetime); create index appointments_barber_idx on appointments(barber_id);
create table business_settings(id int primary key default 1 check(id=1),business_name text default 'Vitinho Barber',phone text,instagram text,address text,map_url text,timezone text default 'America/Sao_Paulo',automatic_confirmation boolean default false,minimum_advance_minutes int default 60,maximum_booking_days int default 45,cancellation_policy text,updated_at timestamptz default now());
create table portfolio(id uuid primary key default gen_random_uuid(),title text,category text,image_url text not null,barber_id uuid references barbers,active boolean default true,created_at timestamptz default now());
create table reviews(id uuid primary key default gen_random_uuid(),customer_name text,rating int check(rating between 1 and 5),comment text,source text,active boolean default false,created_at timestamptz default now());
alter table barbers enable row level security; alter table services enable row level security; alter table appointments enable row level security; alter table customers enable row level security; alter table business_settings enable row level security; alter table portfolio enable row level security; alter table reviews enable row level security;
create policy "public reads active barbers" on barbers for select using(active); create policy "public reads active services" on services for select using(active); create policy "public reads settings" on business_settings for select using(true); create policy "public reads portfolio" on portfolio for select using(active); create policy "public reads reviews" on reviews for select using(active);
create policy "admins manage barbers" on barbers for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "admins manage services" on services for all using(exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "staff read appointments" on appointments for select using(exists(select 1 from profiles p where p.id=auth.uid() and (p.role='admin' or p.barber_id=appointments.barber_id)));
insert into barbers(name,slug,bio,specialties) values
('Vitinho OFC','vitinho-ofc','Perfil oficial da Vitinho Barber.',array['degradê','navalhado','platinado']),
('Pablo','pablo','Corte personalizado e acabamento preciso.',array['corte masculino','barba'])
on conflict(slug) do update set name=excluded.name,bio=excluded.bio,specialties=excluded.specialties;
insert into services(id,name,slug,description,price,duration_minutes) values ('navalhado','Corte navalhado','corte-navalhado','Acabamento preciso na navalha',35,60),('social','Corte social','corte-social','Clássico e versátil',30,60),('combo','Cabelo e barba','cabelo-barba','Visual completo',55,60),('barba','Barba','barba','Contorno e acabamento',25,60),('pezinho','Pezinho','pezinho','Manutenção rápida',15,30),('sobrancelha','Sobrancelha','sobrancelha','Acabamento natural',15,30),('pigmentacao','Pigmentação','pigmentacao','Definição sob medida',20,null),('luzes','Luzes','luzes','Tonalidade personalizada',140,null),('platinado','Platinado','platinado','Transformação completa',140,null);
insert into barber_services(barber_id,service_id) select b.id,s.id from barbers b cross join services s where b.slug in('vitinho-ofc','pablo') on conflict do nothing;
