'use client';
import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,Check,Clock3,LogOut,MessageCircle,RefreshCw,Scissors,UserRound,X} from 'lucide-react';
type Appointment={id:string;start_datetime:string;price:number;status:string;customers:{name:string;phone:string}|null;barbers:{name:string}|null;services:{name:string;duration_minutes:number}|null};
const money=(v:number)=>`R$ ${v.toFixed(2).replace('.',',')}`;

export default function AdminAgenda(){
 const [items,setItems]=useState<Appointment[]>([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState('Todos'),[date,setDate]=useState('');
 async function load(){setLoading(true);const r=await fetch('/api/admin/appointments',{cache:'no-store'});if(r.ok){const d=await r.json();setItems(d.appointments||[]);setDate(d.date)}setLoading(false)}
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
 const barbers=['Todos','Vitinho OFC','Pablo'];
 const shown=filter==='Todos'?items:items.filter(x=>x.barbers?.name===filter);
 const confirmed=items.filter(x=>x.status==='confirmado').length,done=items.filter(x=>x.status==='concluído'),revenue=done.reduce((n,x)=>n+Number(x.price),0),expected=items.filter(x=>!['cancelado','não compareceu'].includes(x.status)).reduce((n,x)=>n+Number(x.price),0),cancelled=items.filter(x=>x.status==='cancelado').length;
 const barberStats=useMemo(()=>Array.from(new Set(items.map(x=>x.barbers?.name).filter(Boolean) as string[])).map(name=>{const list=items.filter(x=>x.barbers?.name===name),completed=list.filter(x=>x.status==='concluído');return{name,count:list.length,completed:completed.length,total:completed.reduce((n,x)=>n+Number(x.price),0)}}),[items]);
 const serviceStats=useMemo(()=>Array.from(new Set(items.map(x=>x.services?.name).filter(Boolean) as string[])).map(name=>({name,count:items.filter(x=>x.services?.name===name&&!['cancelado','não compareceu'].includes(x.status)).length})).sort((a,b)=>b.count-a.count),[items]);
 async function status(id:string,value:string){await fetch('/api/admin/appointments',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status:value})});load()}
 async function logout(){await fetch('/api/logout',{method:'POST'});location.href='/login'}
 return <main className="agendaAdmin"><aside><a className="brand" href="/"><span className="brandmark"><Scissors/></span><b>VITINHO</b><small>GESTÃO</small></a><nav><a className="active"><CalendarDays/>Dashboard</a><a href="/"><Scissors/>Ver site</a></nav><button onClick={logout}><LogOut/>Sair</button></aside><section>
  <header className="agendaTop"><div><small>PAINEL ADMINISTRATIVO</small><h1>Resultado de hoje</h1><p>{new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date())}</p></div><button onClick={load}><RefreshCw className={loading?'spin':''}/>Atualizar</button></header>
  <div className="agendaMetrics"><article><Clock3/><span><small>Agendamentos</small><b>{items.length}</b></span></article><article><Check/><span><small>Confirmados</small><b>{confirmed}</b></span></article><article><span><small>Previsto hoje</small><b>{money(expected)}</b></span></article><article className="revenueCard"><span><small>Faturado hoje</small><b>{money(revenue)}</b></span></article></div>
  <div className="financeGrid"><article><div className="financeTitle"><span><small>RESUMO DO DIA</small><h2>Resultado financeiro</h2></span><b>{date?date.split('-').reverse().join('/'):''}</b></div><div className="financeRows"><p><span>Valor previsto</span><b>{money(expected)}</b></p><p><span>Valor já faturado</span><b className="positive">{money(revenue)}</b></p><p><span>Falta receber</span><b>{money(Math.max(expected-revenue,0))}</b></p><p><span>Cancelamentos</span><b className="negative">{cancelled}</b></p></div></article><article><div className="financeTitle"><span><small>EQUIPE</small><h2>Por barbeiro</h2></span></div><div className="barberStats">{barberStats.length?barberStats.map(b=><div key={b.name}><span><b>{b.name}</b><small>{b.completed}/{b.count} concluídos</small></span><strong>{money(b.total)}</strong></div>):<p className="muted">Sem movimentação hoje.</p>}</div></article><article><div className="financeTitle"><span><small>SERVIÇOS</small><h2>Mais pedidos</h2></span></div><div className="serviceStats">{serviceStats.length?serviceStats.slice(0,5).map((s,i)=><div key={s.name}><b>0{i+1}</b><span>{s.name}</span><strong>{s.count}</strong></div>):<p className="muted">Nenhum serviço agendado.</p>}</div></article></div>
  <div className="agendaToolbar"><b>Agenda de hoje</b><div>{barbers.map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div>
  <div className="agendaList">{loading&&!items.length?<div className="agendaEmpty"><RefreshCw className="spin"/>Carregando agenda...</div>:!shown.length?<div className="agendaEmpty"><CalendarDays/><b>Nenhum horário marcado hoje</b><p>Os novos agendamentos aparecerão aqui automaticamente.</p></div>:shown.map(a=><article key={a.id} className={`appointment ${a.status.replaceAll(' ','-')}`}><time>{new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:'America/Sao_Paulo'}).format(new Date(a.start_datetime))}</time><div className="client"><b><UserRound/>{a.customers?.name}</b><a href={`https://wa.me/55${a.customers?.phone?.replace(/\D/g,'')}`}><MessageCircle/>{a.customers?.phone}</a></div><div><b>{a.services?.name}</b><small>{a.barbers?.name} · {a.services?.duration_minutes||60} min</small></div><span className="status">{a.status}</span><div className="agendaActions"><button title="Confirmar" onClick={()=>status(a.id,'confirmado')}><Check/></button><button title="Concluir" onClick={()=>status(a.id,'concluído')}><Scissors/></button><button title="Cancelar" className="danger" onClick={()=>status(a.id,'cancelado')}><X/></button></div></article>)}</div>
 </section></main>
}
