'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Clock3,LoaderCircle,X} from 'lucide-react';
import {services,whatsapp,address} from '@/lib/data';
const baseTimes=['09:00','10:00','11:00','14:00','15:00','16:00','17:00','18:00','19:00'];
const todayInBrazil=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const bookingDays=()=>Array.from({length:14},(_,index)=>{const base=new Date(`${todayInBrazil()}T12:00:00-03:00`);base.setDate(base.getDate()+index);return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(base)});
const shortDate=(value:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(`${value}T12:00:00-03:00`)).replace('.', '');
const longDate=(value:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'long',day:'2-digit',month:'long'}).format(new Date(`${value}T12:00:00-03:00`));
type Slot={time:string;available:boolean;reason?:string};
const barbers=[{name:'Vitinho OFC',note:'Cortes modernos e transformações'},{name:'Pablo',note:'Corte personalizado e acabamento preciso'}];

export default function Booking(){
 const [step,setStep]=useState(1),[service,setService]=useState(''),[barber,setBarber]=useState('Vitinho OFC'),[date,setDate]=useState(todayInBrazil),[time,setTime]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[done,setDone]=useState(false),[loading,setLoading]=useState(false),[slots,setSlots]=useState<Slot[]>(baseTimes.map(time=>({time,available:true}))),[slotsLoading,setSlotsLoading]=useState(false);
 const days=useMemo(bookingDays,[]);
 const item=useMemo(()=>services.find(x=>x.id===service),[service]);
 useEffect(()=>{if(step!==3||!service)return;setSlotsLoading(true);setTime('');fetch(`/api/availability?date=${date}&barber=${encodeURIComponent(barber)}&service=${service}`).then(r=>r.json()).then(data=>setSlots(data.slots||[])).finally(()=>setSlotsLoading(false))},[step,service,barber,date]);
 const next=()=>setStep(x=>Math.min(4,x+1)),back=()=>setStep(x=>Math.max(1,x-1));
 async function confirm(){if(!item||!name||phone.replace(/\D/g,'').length<10)return;setLoading(true);try{const res=await fetch('/api/appointments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,phone:phone.replace(/\D/g,''),serviceId:service,barberName:barber,date,time})});if(res.ok)setDone(true);else alert((await res.json()).error||'Não foi possível reservar.');}finally{setLoading(false)}}
 if(done){const text=encodeURIComponent(`Olá, agendei um horário pelo site da Vitinho Barber.\n\nNome: ${name}\nServiço: ${item?.name}\nProfissional: ${barber}\nData: ${longDate(date)}\nHorário: ${time}\n\nGostaria de confirmar meu agendamento.`);return <div className="bookingCard success"><div className="successIcon"><Check/></div><h3>Horário reservado!</h3><p>{item?.name} com {barber}<br/><b>{longDate(date)}, às {time}</b></p><small>{address}</small><a className="btn gold" target="_blank" rel="noreferrer" href={`https://wa.me/${whatsapp}?text=${text}`}>Confirmar pelo WhatsApp</a></div>}
 return <div className="bookingCard"><div className="bookingHeader"><div><small>RESERVA RÁPIDA</small><b>{item?.name||'Monte seu atendimento'}</b></div><span>{step}/4</span></div><div className="progress bookingProgress">{['Serviço','Barbeiro','Horário','Dados'].map((label,i)=><div className={step>=i+1?'active':''} key={label}><span>{step>i+1?<Check/>:i+1}</span><small>{label}</small></div>)}</div>
 {step===1&&<div><h3>Escolha o serviço</h3><div className="choices">{services.map(s=><button type="button" className={service===s.id?'selected':''} onClick={()=>setService(s.id)} key={s.id}><span><b>{s.name}</b><small>{s.duration?`${s.duration} min`:'Sob consulta'}</small></span><strong>R$ {s.price}</strong></button>)}</div></div>}
 {step===2&&<div><h3>Escolha o profissional</h3><div className="choices barberChoices">{barbers.map(b=><button type="button" className={barber===b.name?'selected':''} onClick={()=>setBarber(b.name)} key={b.name}><span><b>{b.name}</b><small>{b.note}</small></span>{barber===b.name&&<Check/>}</button>)}</div></div>}
 {step===3&&<div><h3>Escolha dia e horário</h3><div className="dateChoices" aria-label="Dias disponíveis">{days.map(day=><button type="button" className={date===day?'selected':''} onClick={()=>setDate(day)} key={day}><span>{shortDate(day).split(',')[0]}</span><b>{shortDate(day).split(',')[1]}</b></button>)}</div><p className="todayLabel">{longDate(date)} · {barber}</p>{slotsLoading?<div className="slotLoading"><LoaderCircle/> Consultando agenda...</div>:slots.length?<div className="times">{slots.map(s=><button type="button" disabled={!s.available} className={`${time===s.time?'selected':''} ${!s.available?'occupied':''}`} onClick={()=>setTime(s.time)} key={s.time}>{s.available?<Clock3/>:<X/>}<span>{s.time}</span>{!s.available&&<small>{s.reason==='ocupado'?'OCUPADO':'INDISPONÍVEL'}</small>}</button>)}</div>:<p className="noSlots">Não há horários disponíveis nesta data. Escolha outro dia ou fale com a gente pelo WhatsApp.</p>}</div>}
 {step===4&&<div><h3>Confirme seus dados</h3><label>Nome completo<input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome" autoComplete="name"/></label><label>WhatsApp<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(51) 99999-9999" inputMode="tel" autoComplete="tel"/></label><div className="summary"><span>{item?.name}</span><b>R$ {item?.price.toFixed(2).replace('.',',')}</b><small>{barber} · {longDate(date)} às {time}</small></div></div>}
 <div className="bookNav">{step>1&&<button className="back" onClick={back}><ArrowLeft/> Voltar</button>}{step<4?<button className="btn gold" disabled={(step===1&&!service)||(step===3&&!time)} onClick={next}>Continuar <ArrowRight/></button>:<button className="btn gold" disabled={loading||!name||phone.replace(/\D/g,'').length<10} onClick={confirm}>{loading?'Salvando...':'Confirmar agendamento'} <Check/></button>}</div></div>
}
