import {NextRequest,NextResponse} from 'next/server';
import {createAdminClient} from '@/utils/supabase/server';
import {demoAppointments} from '@/lib/demo-appointments';
import {services} from '@/lib/data';
type Range={start_datetime:string;end_datetime:string};
const fallbackHours=(day:number)=>day===0?null:day===1?{start:'14:00',end:'20:00'}:{start:'09:00',end:'20:00'};
const mins=(v:string)=>{const [h,m]=v.slice(0,5).split(':').map(Number);return h*60+m},clock=(v:number)=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`;
const overlaps=(s:Date,e:Date,r:Range[])=>r.some(x=>s<new Date(x.end_datetime)&&e>new Date(x.start_datetime));
export async function GET(req:NextRequest){
 const date=req.nextUrl.searchParams.get('date'),barberName=req.nextUrl.searchParams.get('barber'),serviceId=req.nextUrl.searchParams.get('service');if(!date||!barberName||!serviceId)return NextResponse.json({error:'Parâmetros incompletos'},{status:400});
 const weekday=new Date(`${date}T12:00:00-03:00`).getDay(),defaults=fallbackHours(weekday),db=createAdminClient();if(!defaults)return NextResponse.json({slots:[],closed:true,message:'Fechado aos domingos.'});
 if(!db){const duration=services.find(service=>service.id===serviceId)?.duration||60,step=duration<=30?30:60,slots=[];for(let n=mins(defaults.start);n+duration<=mins(defaults.end);n+=step){const time=clock(n),start=new Date(`${date}T${time}:00-03:00`),occupied=demoAppointments.some(a=>a.date===date&&a.barber===barberName&&a.time===time);slots.push({time,available:start.getTime()>Date.now()&&!occupied,reason:occupied?'ocupado':start.getTime()<=Date.now()?'encerrado':undefined})}return NextResponse.json({slots,duration,demo:true});}
 const {data:barbers}=await db.from('barbers').select('id,name').eq('active',true),barber=barbers?.find(b=>b.name===barberName);if(!barber)return NextResponse.json({error:'Profissional não encontrado'},{status:404});
 const dayStart=new Date(`${date}T00:00:00-03:00`),dayEnd=new Date(`${date}T23:59:59-03:00`);const [{data:service},{data:hours},{data:breaks},{data:busy},{data:blocked}]=await Promise.all([db.from('services').select('duration_minutes').eq('id',serviceId).eq('active',true).single(),db.from('working_hours').select('start_time,end_time').eq('barber_id',barber.id).eq('weekday',weekday).eq('active',true).maybeSingle(),db.from('breaks').select('start_time,end_time').eq('barber_id',barber.id).eq('weekday',weekday),db.from('appointments').select('start_datetime,end_datetime').eq('barber_id',barber.id).gte('start_datetime',dayStart.toISOString()).lte('start_datetime',dayEnd.toISOString()).not('status','in','("cancelado","não compareceu")'),db.from('blocked_times').select('start_datetime,end_datetime').eq('barber_id',barber.id).lt('start_datetime',dayEnd.toISOString()).gt('end_datetime',dayStart.toISOString())]);
 const open=hours?{start:hours.start_time.slice(0,5),end:hours.end_time.slice(0,5)}:defaults,duration=service?.duration_minutes||60,step=duration<=30?30:60,ranges:Range[]=[...(busy||[]),...(blocked||[]),...(breaks||[]).map(b=>({start_datetime:`${date}T${b.start_time.slice(0,5)}:00-03:00`,end_datetime:`${date}T${b.end_time.slice(0,5)}:00-03:00`}))],slots=[];
 for(let n=mins(open.start);n+duration<=mins(open.end);n+=step){const time=clock(n),start=new Date(`${date}T${time}:00-03:00`),end=new Date(start.getTime()+duration*60000),occupied=overlaps(start,end,ranges),past=start.getTime()<=Date.now();slots.push({time,available:!past&&!occupied,reason:occupied?'ocupado':past?'encerrado':undefined})}return NextResponse.json({slots,duration,professional:barber.name});
}
